sources:
  include:
    - Sources/CombineBluetooth
templates:
  - Tools/Sourcery/Templates
output:
  Sources/CombineBluetoothMocks
args:
  autoMockableImports: ["Combine", "CombineBluetooth", "CoreBluetooth"]
  autoMockableTestableImports: []
